import { inter } from '@/fonts/basic-fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'DreamSpace Interiors | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
